// Generated by setup.html on 2026-09-12T02:32:42.007Z
// This file holds YOUR project's key - keep it next to index.html.
window.SUPABASE_URL = "https://iszsdvdtkfdvoagpyvfl.supabase.co";
window.SUPABASE_KEY = "sb_publishable_0NBdN51ASUas1NvYZohuXQ_zCbNCPJL";
